#Usage: python run_openAPS_monitor.py target_fault_library_monitor_V2
python run_openAPS_monitor.py fault_library_monitor_V2_STPA/scenario_9
python run_openAPS_monitor.py fault_library_monitor_V2_STPA/scenario_12
python run_openAPS_monitor.py fault_library_monitor_V2_STPA/scenario_13
python run_openAPS_monitor.py fault_library_monitor_V2_STPA/scenario_14
python run_openAPS_monitor.py fault_library_monitor_V2_STPA/scenario_17
python run_openAPS_monitor.py fault_library_monitor_V2_STPA/scenario_18
python run_openAPS_monitor.py fault_library_monitor_V2_STPA/scenario_19
python run_openAPS_monitor.py fault_library_monitor_V2_STPA/scenario_20
python run_openAPS_monitor.py fault_library_monitor_V2_STPA/scenario_21
python run_openAPS_monitor.py fault_library_monitor_V2_STPA/scenario_22
