#Usage: python run_openAPS.py target_fault_library_monitor
python run_openAPS.py fault_library_monitor_STPA/scenario_1
python run_openAPS.py fault_library_monitor_STPA/scenario_2
python run_openAPS.py fault_library_monitor_STPA/scenario_3
python run_openAPS.py fault_library_monitor_STPA/scenario_4
python run_openAPS.py fault_library_monitor_STPA/scenario_5
python run_openAPS.py fault_library_monitor_STPA/scenario_6
python run_openAPS.py fault_library_monitor_STPA/scenario_7
python run_openAPS.py fault_library_monitor_STPA/scenario_8
